version: '3.4'
services:
  database:
    hostname: mysql
    image: mysql
    ports:
      - 3306:3306
      - 30306:30306
    environment:
      - MYSQL_ROOT_PASSWORD=as1234
    volumes:
      - database_volume:/var/lib/mysql
    restart: always
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
  referee:
    build:
      context: ./ace-judge-referee
      target: development
    environment:
      - BROKER_URL=amqp://guest@rabbitmq:5672//
      - BACKEND_URL=rpc://
    depends_on:
      - server
  web:
    build:
      context: ./ace-judge-client
      target: development
      args: 
        - ENV=
    ports:
      - 4200:4200
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=8080
    depends_on:
      - server
    volumes: 
      - ./ace-judge-client/src:/ng-app/src
  server:
    build:
      context: ./ace-judge-server
    ports:
      - 8080:8080
    depends_on:
      - database
      - rabbitmq
    environment: 
      - MYSQL_HOST=database
      - MYSQL_DATABASE=ace
      - MYSQL_USER=ace
      - MYSQL_PASS=as1234
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - FILE_UPLOAD_DIR=/upload-dir
    volumes:
      - uploads_volume:/upload-dir
      - "${HOME}/.m2:/root/.m2"
    restart: always
volumes: 
  database_volume:
  uploads_volume: