version: '3'
services:
  ace-judge-database:
    hostname: mysql
    image: mysql
    ports:
      - 3306:3306
      - 30306:30306
    environment: 
      - MYSQL_ROOT_PASSWORD=as1234
  ace-judge-rabbitmq:
    hostname: rabbitmq
    image: rabbitmq
    ports:
      - 5672:5672
  ace-judge-referee:
    image: nginx
  ace-judge-web:
    build:
      context: ./ace-judge-client
    ports:
      - 80:4200
    depends_on:
      - ace-judge-server
  ace-judge-server:
    build:
      context: ./ace-judge-server
    ports:
      - 8080:8080
    depends_on:
      - ace-judge-database
      - ace-judge-rabbitmq